spring.application.name=HUmlTool
# 1. C?u hình k?t n?i MongoDB
# huml_db là tên database, nó s? t? t?o n?u ch?a có
spring.data.mongodb.uri=mongodb://localhost:27017/huml_db

# 2. C?u hình Server (M?c ??nh là 8080, có th? ??i n?u trùng)
server.port=8080

# 3. Hi?n th? log truy v?n (R?t quan tr?ng ?? debug lúc m?i làm)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# 4. T?t banner Spring Boot cho g?n console (tùy ch?n)
spring.main.banner-mode=off